// <auto-generated />
using System;
using KnowledgeBase.Core.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KnowledgeBase.Core.Persistence.Migrations
{
    [DbContext(typeof(KnowledgeBaseDbContext))]
    [Migration("20260916122024_AddSceneAnalysisFoundation")]
    partial class AddSceneAnalysisFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.ArchiveEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LocationId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateOnly?>("OccurredOn")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("ArchiveEvents");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.ArchiveEventPerson", b =>
                {
                    b.Property<string>("EventId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PersonId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("EventId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("ArchiveEventPeople");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.ArchiveEventPhoto", b =>
                {
                    b.Property<string>("EventId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("AssetId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("EventId", "AssetId");

                    b.HasIndex("AssetId");

                    b.ToTable("ArchiveEventPhotos");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.AssetRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContentSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContentSha256");

                    b.HasIndex("StoredFileName")
                        .IsUnique();

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.FaceOccurrence", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DetectionScore")
                        .HasColumnType("double precision");

                    b.Property<float[]>("Embedding")
                        .IsRequired()
                        .HasColumnType("real[]");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("LandmarksJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.Property<int>("X")
                        .HasColumnType("integer");

                    b.Property<int>("Y")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.HasIndex("AssetId", "CreatedAtUtc");

                    b.ToTable("FaceOccurrences");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.Location", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Kind")
                        .IsUnique();

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.LocationObservation", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("ConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SourceDecisionId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("VisualEmbeddingId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("LocationId");

                    b.HasIndex("SourceDecisionId")
                        .IsUnique();

                    b.HasIndex("VisualEmbeddingId")
                        .IsUnique();

                    b.ToTable("LocationObservations");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.Note", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("SourceAssetId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SourceFileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SynthesisGroup")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SourceAssetId");

                    b.HasIndex("Title")
                        .IsUnique()
                        .HasFilter("\"DeletedAtUtc\" IS NULL");

                    b.HasIndex("Kind", "SynthesisGroup")
                        .IsUnique()
                        .HasFilter("\"SynthesisGroup\" IS NOT NULL AND \"DeletedAtUtc\" IS NULL");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.NoteLink", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SourceNoteId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TargetNoteId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TargetTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("TargetNoteId");

                    b.HasIndex("TargetTitle");

                    b.HasIndex("SourceNoteId", "TargetTitle")
                        .IsUnique();

                    b.ToTable("NoteLinks");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.NoteTag", b =>
                {
                    b.Property<string>("NoteId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TagId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.HasKey("NoteId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("NoteTags");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.Person", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("People");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.PersonReferenceFace", b =>
                {
                    b.Property<string>("FaceOccurrenceId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("ConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PersonId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SourceDecisionId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("FaceOccurrenceId");

                    b.HasIndex("PersonId");

                    b.HasIndex("SourceDecisionId");

                    b.ToTable("PersonReferenceFaces");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.PhotoAnalysisCandidate", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("ProposedLabel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProposedTargetId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<string>("SignalsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SubjectAssetId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SubjectFaceOccurrenceId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("SubjectAssetId");

                    b.HasIndex("SubjectFaceOccurrenceId");

                    b.HasIndex("RunId", "SubjectFaceOccurrenceId", "Kind", "Rank")
                        .IsUnique();

                    b.ToTable("PhotoAnalysisCandidates");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.PhotoAnalysisReviewDecision", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("CandidateId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ChosenTargetId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("DecidedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId", "DecidedAtUtc");

                    b.ToTable("PhotoAnalysisReviewDecisions");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.PhotoAnalysisRun", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConfigurationHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ModelKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PipelineVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId", "CompletedAtUtc");

                    b.ToTable("PhotoAnalysisRuns");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.ProcessingJob", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("AssetId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Payload")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId", "Kind")
                        .IsUnique()
                        .HasFilter("\"AssetId\" IS NOT NULL");

                    b.HasIndex("Status", "CreatedAtUtc");

                    b.ToTable("ProcessingJobs");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.SynthesisSource", b =>
                {
                    b.Property<string>("SynthesisNoteId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("InputNoteId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("SynthesisNoteId", "InputNoteId");

                    b.HasIndex("InputNoteId");

                    b.ToTable("SynthesisSources");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.Tag", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SuggestedMergeConfidence")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("SuggestedMergeIntoId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SuggestedMergeIntoId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.TagParent", b =>
                {
                    b.Property<string>("ChildId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ParentId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("ChildId", "ParentId");

                    b.HasIndex("ParentId");

                    b.ToTable("TagParents");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.TagParentSuggestion", b =>
                {
                    b.Property<string>("ChildId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ParentId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("DeclineCount")
                        .HasColumnType("integer");

                    b.Property<bool>("Dismissed")
                        .HasColumnType("boolean");

                    b.HasKey("ChildId", "ParentId");

                    b.HasIndex("ParentId");

                    b.ToTable("TagParentSuggestions");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.VisualEmbedding", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float[]>("Embedding")
                        .IsRequired()
                        .HasColumnType("real[]");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("RunId")
                        .IsUnique();

                    b.HasIndex("AssetId", "CreatedAtUtc");

                    b.ToTable("VisualEmbeddings");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.ArchiveEvent", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.ArchiveEventPerson", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.ArchiveEvent", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeBase.Core.Persistence.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.ArchiveEventPhoto", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.AssetRecord", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeBase.Core.Persistence.ArchiveEvent", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.FaceOccurrence", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.AssetRecord", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeBase.Core.Persistence.PhotoAnalysisRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.LocationObservation", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.AssetRecord", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeBase.Core.Persistence.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeBase.Core.Persistence.PhotoAnalysisReviewDecision", null)
                        .WithMany()
                        .HasForeignKey("SourceDecisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeBase.Core.Persistence.VisualEmbedding", null)
                        .WithMany()
                        .HasForeignKey("VisualEmbeddingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.Note", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.AssetRecord", null)
                        .WithMany()
                        .HasForeignKey("SourceAssetId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.NoteLink", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.Note", null)
                        .WithMany()
                        .HasForeignKey("SourceNoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeBase.Core.Persistence.Note", null)
                        .WithMany()
                        .HasForeignKey("TargetNoteId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.NoteTag", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.Note", null)
                        .WithMany()
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeBase.Core.Persistence.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.PersonReferenceFace", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.FaceOccurrence", null)
                        .WithMany()
                        .HasForeignKey("FaceOccurrenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeBase.Core.Persistence.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeBase.Core.Persistence.PhotoAnalysisReviewDecision", null)
                        .WithMany()
                        .HasForeignKey("SourceDecisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.PhotoAnalysisCandidate", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.PhotoAnalysisRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeBase.Core.Persistence.AssetRecord", null)
                        .WithMany()
                        .HasForeignKey("SubjectAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeBase.Core.Persistence.FaceOccurrence", null)
                        .WithMany()
                        .HasForeignKey("SubjectFaceOccurrenceId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.PhotoAnalysisReviewDecision", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.PhotoAnalysisCandidate", null)
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.PhotoAnalysisRun", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.AssetRecord", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.ProcessingJob", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.AssetRecord", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.SynthesisSource", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.Note", null)
                        .WithMany()
                        .HasForeignKey("InputNoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeBase.Core.Persistence.Note", null)
                        .WithMany()
                        .HasForeignKey("SynthesisNoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.Tag", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.Tag", null)
                        .WithMany()
                        .HasForeignKey("SuggestedMergeIntoId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.TagParent", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.Tag", null)
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeBase.Core.Persistence.Tag", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.TagParentSuggestion", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.Tag", null)
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeBase.Core.Persistence.Tag", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.VisualEmbedding", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.AssetRecord", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeBase.Core.Persistence.PhotoAnalysisRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
