// <auto-generated />
using System;
using KnowledgeBase.Core.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KnowledgeBase.Core.Persistence.Migrations
{
    [DbContext(typeof(KnowledgeBaseDbContext))]
    [Migration("20260923085910_AddFaceComparisonReview")]
    partial class AddFaceComparisonReview
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.ArchiveEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LocationId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateOnly?>("OccurredOn")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("ArchiveEvents");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.ArchiveEventPerson", b =>
                {
                    b.Property<string>("EventId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PersonId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("EventId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("ArchiveEventPeople");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.ArchiveEventPhoto", b =>
                {
                    b.Property<string>("EventId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("AssetId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("EventId", "AssetId");

                    b.HasIndex("AssetId");

                    b.ToTable("ArchiveEventPhotos");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.AssetRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContentSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContentSha256");

                    b.HasIndex("StoredFileName")
                        .IsUnique();

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.EventCandidate", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ClusterId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<DateOnly?>("SuggestedOccurredOn")
                        .HasColumnType("date");

                    b.Property<DateTime?>("SupersededAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId", "CreatedAtUtc")
                        .IsUnique();

                    b.HasIndex("SupersededAtUtc", "CreatedAtUtc");

                    b.ToTable("EventCandidates");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.EventCandidateReviewDecision", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("CandidateId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ChosenEventId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("DecidedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("SelectedAssetIdsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId")
                        .IsUnique();

                    b.ToTable("EventCandidateReviewDecisions");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.EventCluster", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<string>("SignalsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("SupersededAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "Score");

                    b.ToTable("EventClusters");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.EventClusterPhoto", b =>
                {
                    b.Property<string>("ClusterId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("AssetId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("ClusterId", "AssetId");

                    b.HasIndex("AssetId");

                    b.ToTable("EventClusterPhotos");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.EventClusteringRun", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConfigurationHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ModelKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PipelineVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CompletedAtUtc");

                    b.ToTable("EventClusteringRuns");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.FaceCluster", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HintPersonId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<double?>("HintScore")
                        .HasColumnType("double precision");

                    b.Property<string>("IgnoredGroupId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("PersonId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("IgnoredGroupId");

                    b.HasIndex("RunId", "Kind");

                    b.ToTable("FaceClusters");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.FaceClusteringRun", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConfigurationHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PipelineVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CompletedAtUtc");

                    b.ToTable("FaceClusteringRuns");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.FaceComparisonDetection", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<bool?>("IsFace")
                        .HasColumnType("boolean");

                    b.Property<string>("LandmarksJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<string>("ResultId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<string>("WarningsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<float>("Width")
                        .HasColumnType("real");

                    b.Property<float>("X")
                        .HasColumnType("real");

                    b.Property<float>("Y")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ResultId", "Ordinal")
                        .IsUnique();

                    b.ToTable("FaceComparisonDetections");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.FaceComparisonResult", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<double?>("ElapsedMilliseconds")
                        .HasColumnType("double precision");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("MissedFaces")
                        .HasColumnType("integer");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "ModelId")
                        .IsUnique();

                    b.ToTable("FaceComparisonResults");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.FaceComparisonRun", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ContentSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ImageHeight")
                        .HasColumnType("integer");

                    b.Property<int?>("ImageWidth")
                        .HasColumnType("integer");

                    b.Property<bool>("IsSkipped")
                        .HasColumnType("boolean");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("JobId")
                        .IsUnique();

                    b.HasIndex("AssetId", "CreatedAtUtc");

                    b.ToTable("FaceComparisonRuns");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.FaceIdentity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.ToTable("FaceIdentities");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.FaceOccurrence", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DetectionScore")
                        .HasColumnType("double precision");

                    b.Property<float[]>("Embedding")
                        .IsRequired()
                        .HasColumnType("real[]");

                    b.Property<string>("EmbeddingModelKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("IdentityId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsPartial")
                        .HasColumnType("boolean");

                    b.Property<string>("LandmarksJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.Property<int>("X")
                        .HasColumnType("integer");

                    b.Property<int>("Y")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdentityId");

                    b.HasIndex("RunId");

                    b.HasIndex("AssetId", "CreatedAtUtc");

                    b.ToTable("FaceOccurrences");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.FaceRecognitionComparisonEmbedding", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float[]>("Embedding")
                        .IsRequired()
                        .HasColumnType("real[]");

                    b.Property<string>("FaceOccurrenceId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.HasIndex("FaceOccurrenceId", "ModelId")
                        .IsUnique();

                    b.ToTable("FaceRecognitionComparisonEmbeddings");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.FaceRecognitionComparisonPair", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("FirstFaceOccurrenceId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsSamePerson")
                        .HasColumnType("boolean");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SecondFaceOccurrenceId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "FirstFaceOccurrenceId", "SecondFaceOccurrenceId")
                        .IsUnique();

                    b.ToTable("FaceRecognitionComparisonPairs");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.FaceRecognitionComparisonResult", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("DifferentPersonPairs")
                        .HasColumnType("integer");

                    b.Property<double?>("ElapsedMilliseconds")
                        .HasColumnType("double precision");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("FalseNegatives")
                        .HasColumnType("integer");

                    b.Property<int>("FalsePositives")
                        .HasColumnType("integer");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("SamePersonPairs")
                        .HasColumnType("integer");

                    b.Property<double?>("Threshold")
                        .HasColumnType("double precision");

                    b.Property<int>("TrueNegatives")
                        .HasColumnType("integer");

                    b.Property<int>("TruePositives")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "ModelId")
                        .IsUnique();

                    b.ToTable("FaceRecognitionComparisonResults");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.FaceRecognitionComparisonRun", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("PersonCount")
                        .HasColumnType("integer");

                    b.Property<int>("PhotoCount")
                        .HasColumnType("integer");

                    b.Property<int>("ReferenceFaceCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("JobId")
                        .IsUnique();

                    b.ToTable("FaceRecognitionComparisonRuns");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.FaceRecognitionComparisonScore", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsMatch")
                        .HasColumnType("boolean");

                    b.Property<string>("PairId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ResultId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ResultId");

                    b.HasIndex("PairId", "ResultId")
                        .IsUnique();

                    b.ToTable("FaceRecognitionComparisonScores");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.IgnoredFaceGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.ToTable("IgnoredFaceGroups");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.Location", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Kind")
                        .IsUnique();

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.LocationObservation", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("ConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SourceDecisionId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("VisualEmbeddingId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("LocationId");

                    b.HasIndex("SourceDecisionId")
                        .IsUnique();

                    b.HasIndex("VisualEmbeddingId")
                        .IsUnique();

                    b.ToTable("LocationObservations");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.Note", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("SourceAssetId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SourceFileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SynthesisGroup")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SourceAssetId");

                    b.HasIndex("Title")
                        .IsUnique()
                        .HasFilter("\"DeletedAtUtc\" IS NULL");

                    b.HasIndex("Kind", "SynthesisGroup")
                        .IsUnique()
                        .HasFilter("\"SynthesisGroup\" IS NOT NULL AND \"DeletedAtUtc\" IS NULL");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.NoteLink", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SourceNoteId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TargetNoteId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TargetTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("TargetNoteId");

                    b.HasIndex("TargetTitle");

                    b.HasIndex("SourceNoteId", "TargetTitle")
                        .IsUnique();

                    b.ToTable("NoteLinks");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.NoteTag", b =>
                {
                    b.Property<string>("NoteId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TagId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.HasKey("NoteId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("NoteTags");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.Person", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("People");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.PersonReferenceFace", b =>
                {
                    b.Property<string>("FaceOccurrenceId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("ConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PersonId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SourceDecisionId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("FaceOccurrenceId");

                    b.HasIndex("PersonId");

                    b.HasIndex("SourceDecisionId");

                    b.ToTable("PersonReferenceFaces");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.PhotoAnalysisCandidate", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FaceClusterId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("ProposedLabel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProposedTargetId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<string>("SignalsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SubjectAssetId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SubjectFaceOccurrenceId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("SupersededAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FaceClusterId");

                    b.HasIndex("SubjectAssetId");

                    b.HasIndex("SubjectFaceOccurrenceId");

                    b.HasIndex("Kind", "SubjectAssetId", "SupersededAtUtc");

                    b.HasIndex("RunId", "SubjectFaceOccurrenceId", "Kind", "Rank");

                    b.ToTable("PhotoAnalysisCandidates");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.PhotoAnalysisReviewDecision", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("CandidateId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ChosenTargetId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("DecidedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId", "DecidedAtUtc");

                    b.ToTable("PhotoAnalysisReviewDecisions");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.PhotoAnalysisRun", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConfigurationHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ModelKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PipelineVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId", "CompletedAtUtc");

                    b.ToTable("PhotoAnalysisRuns");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.ProcessingJob", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("AssetId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Payload")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId", "Kind")
                        .IsUnique()
                        .HasFilter("\"AssetId\" IS NOT NULL");

                    b.HasIndex("Status", "CreatedAtUtc");

                    b.ToTable("ProcessingJobs");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.SceneObservation", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("RelatedPersonId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("RelatedPersonName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SubjectPersonId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SubjectPersonName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTime?>("SupersededAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RelatedPersonId");

                    b.HasIndex("RunId");

                    b.HasIndex("SubjectPersonId");

                    b.HasIndex("AssetId", "SupersededAtUtc");

                    b.ToTable("SceneObservations");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.SceneObservationReviewDecision", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("DecidedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ObservationId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("ObservationId")
                        .IsUnique();

                    b.ToTable("SceneObservationReviewDecisions");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.SynthesisSource", b =>
                {
                    b.Property<string>("SynthesisNoteId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("InputNoteId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("SynthesisNoteId", "InputNoteId");

                    b.HasIndex("InputNoteId");

                    b.ToTable("SynthesisSources");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.Tag", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SuggestedMergeConfidence")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("SuggestedMergeIntoId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SuggestedMergeIntoId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.TagParent", b =>
                {
                    b.Property<string>("ChildId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ParentId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("ChildId", "ParentId");

                    b.HasIndex("ParentId");

                    b.ToTable("TagParents");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.TagParentSuggestion", b =>
                {
                    b.Property<string>("ChildId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ParentId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("DeclineCount")
                        .HasColumnType("integer");

                    b.Property<bool>("Dismissed")
                        .HasColumnType("boolean");

                    b.HasKey("ChildId", "ParentId");

                    b.HasIndex("ParentId");

                    b.ToTable("TagParentSuggestions");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.UserAccount", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "00000000000000000000000000000001",
                            CreatedAtUtc = new DateTime(2026, 9, 18, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.UserPreference", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("UserId", "Key");

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.VisualEmbedding", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float[]>("Embedding")
                        .IsRequired()
                        .HasColumnType("real[]");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("RunId")
                        .IsUnique();

                    b.HasIndex("AssetId", "CreatedAtUtc");

                    b.ToTable("VisualEmbeddings");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.ArchiveEvent", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.ArchiveEventPerson", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.ArchiveEvent", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeBase.Core.Persistence.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.ArchiveEventPhoto", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.AssetRecord", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeBase.Core.Persistence.ArchiveEvent", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.EventCandidate", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.EventCluster", null)
                        .WithMany()
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.EventCandidateReviewDecision", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.EventCandidate", null)
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.EventCluster", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.EventClusteringRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.EventClusterPhoto", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.AssetRecord", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeBase.Core.Persistence.EventCluster", null)
                        .WithMany()
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.FaceCluster", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.IgnoredFaceGroup", null)
                        .WithMany()
                        .HasForeignKey("IgnoredGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KnowledgeBase.Core.Persistence.FaceClusteringRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.FaceComparisonDetection", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.FaceComparisonResult", null)
                        .WithMany("Detections")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.FaceComparisonResult", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.FaceComparisonRun", null)
                        .WithMany("Results")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.FaceComparisonRun", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.AssetRecord", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeBase.Core.Persistence.ProcessingJob", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.FaceIdentity", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.AssetRecord", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.FaceOccurrence", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.AssetRecord", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeBase.Core.Persistence.FaceIdentity", null)
                        .WithMany()
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KnowledgeBase.Core.Persistence.PhotoAnalysisRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.FaceRecognitionComparisonEmbedding", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.FaceOccurrence", null)
                        .WithMany()
                        .HasForeignKey("FaceOccurrenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeBase.Core.Persistence.FaceRecognitionComparisonRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.FaceRecognitionComparisonPair", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.FaceRecognitionComparisonRun", null)
                        .WithMany("Pairs")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.FaceRecognitionComparisonResult", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.FaceRecognitionComparisonRun", null)
                        .WithMany("Results")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.FaceRecognitionComparisonRun", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.ProcessingJob", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.FaceRecognitionComparisonScore", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.FaceRecognitionComparisonPair", null)
                        .WithMany("Scores")
                        .HasForeignKey("PairId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeBase.Core.Persistence.FaceRecognitionComparisonResult", null)
                        .WithMany("Scores")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.LocationObservation", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.AssetRecord", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeBase.Core.Persistence.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeBase.Core.Persistence.PhotoAnalysisReviewDecision", null)
                        .WithMany()
                        .HasForeignKey("SourceDecisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeBase.Core.Persistence.VisualEmbedding", null)
                        .WithMany()
                        .HasForeignKey("VisualEmbeddingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.Note", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.AssetRecord", null)
                        .WithMany()
                        .HasForeignKey("SourceAssetId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.NoteLink", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.Note", null)
                        .WithMany()
                        .HasForeignKey("SourceNoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeBase.Core.Persistence.Note", null)
                        .WithMany()
                        .HasForeignKey("TargetNoteId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.NoteTag", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.Note", null)
                        .WithMany()
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeBase.Core.Persistence.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.PersonReferenceFace", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.FaceOccurrence", null)
                        .WithMany()
                        .HasForeignKey("FaceOccurrenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeBase.Core.Persistence.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeBase.Core.Persistence.PhotoAnalysisReviewDecision", null)
                        .WithMany()
                        .HasForeignKey("SourceDecisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.PhotoAnalysisCandidate", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.FaceCluster", null)
                        .WithMany()
                        .HasForeignKey("FaceClusterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KnowledgeBase.Core.Persistence.PhotoAnalysisRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeBase.Core.Persistence.AssetRecord", null)
                        .WithMany()
                        .HasForeignKey("SubjectAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeBase.Core.Persistence.FaceOccurrence", null)
                        .WithMany()
                        .HasForeignKey("SubjectFaceOccurrenceId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.PhotoAnalysisReviewDecision", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.PhotoAnalysisCandidate", null)
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.PhotoAnalysisRun", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.AssetRecord", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.ProcessingJob", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.AssetRecord", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.SceneObservation", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.AssetRecord", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeBase.Core.Persistence.Person", null)
                        .WithMany()
                        .HasForeignKey("RelatedPersonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KnowledgeBase.Core.Persistence.PhotoAnalysisRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeBase.Core.Persistence.Person", null)
                        .WithMany()
                        .HasForeignKey("SubjectPersonId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.SceneObservationReviewDecision", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.SceneObservation", null)
                        .WithMany()
                        .HasForeignKey("ObservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.SynthesisSource", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.Note", null)
                        .WithMany()
                        .HasForeignKey("InputNoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeBase.Core.Persistence.Note", null)
                        .WithMany()
                        .HasForeignKey("SynthesisNoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.Tag", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.Tag", null)
                        .WithMany()
                        .HasForeignKey("SuggestedMergeIntoId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.TagParent", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.Tag", null)
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeBase.Core.Persistence.Tag", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.TagParentSuggestion", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.Tag", null)
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeBase.Core.Persistence.Tag", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.UserPreference", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.VisualEmbedding", b =>
                {
                    b.HasOne("KnowledgeBase.Core.Persistence.AssetRecord", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeBase.Core.Persistence.PhotoAnalysisRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.FaceComparisonResult", b =>
                {
                    b.Navigation("Detections");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.FaceComparisonRun", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.FaceRecognitionComparisonPair", b =>
                {
                    b.Navigation("Scores");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.FaceRecognitionComparisonResult", b =>
                {
                    b.Navigation("Scores");
                });

            modelBuilder.Entity("KnowledgeBase.Core.Persistence.FaceRecognitionComparisonRun", b =>
                {
                    b.Navigation("Pairs");

                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
